spring:
  application:
    name: panggilan-loket
  datasource:
    url: ${DB_URL:jdbc:mysql://172.16.1.27:3306/sik3?useSSL=false&serverTimezone=Asia/Makassar}
    username: ${DB_USERNAME:yanekaputra}
    password: ${DB_PASSWORD:lopakun}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

queue:
  counters:
    - id: A
      name: Loket A
    - id: B
      name: Loket B
    - id: C
      name: Loket C

printer:
  ticket:
    enabled: true
    institution-name: "RS CAHAYA MEDIKA"
    address: "jl. Gajah Mada, Kel. Leneng, Praya, Loteng"
